"""empty message

Revision ID: 0f70bd98ccb8
Revises: 
Create Date: 2022-06-17 20:40:10.521631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f70bd98ccb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('role', sa.String(length=30), nullable=True))
    op.add_column('teacher', sa.Column('role', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'role')
    op.drop_column('student', 'role')
    # ### end Alembic commands ###
