"""empty message

Revision ID: 269cdd346459
Revises: 
Create Date: 2022-06-21 22:36:07.821241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269cdd346459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'timetable', 'subject', ['Thu5'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Thu4'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Wed3'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Wed2'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Tue4'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Mon5'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Mon3'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Wed1'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Fri4'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Thu3'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Thu1'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Tue1'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Mon1'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Tue3'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Fri5'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Wed4'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Mon2'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Mon4'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Tue2'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Tue5'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Fri3'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Thu2'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Fri1'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Wed5'], ['id'])
    op.create_foreign_key(None, 'timetable', 'subject', ['Fri2'], ['id'])
    # ### end Alembic commands ###
