"""empty message

Revision ID: 8e76e429f6f3
Revises: 
Create Date: 2022-06-21 00:46:17.991570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e76e429f6f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_column('marks', 'semester')
    op.drop_column('subject', 'semester')
    op.drop_column('subject', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('teacher', sa.INTEGER(), nullable=True))
    op.add_column('subject', sa.Column('semester', sa.INTEGER(), nullable=True))
    op.add_column('marks', sa.Column('semester', sa.INTEGER(), nullable=True))
    op.create_table('timetable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
