"""empty message

Revision ID: 8fabcd0c342f
Revises: 
Create Date: 2022-07-21 21:58:37.875470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fabcd0c342f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('marks')
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_table('teacher')
    op.drop_table('admin')
    op.drop_table('timetable')
    op.drop_table('complaints')
    op.drop_table('branch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('year_started', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('complaint', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dept', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['dept'], ['admin.dept'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('Mon1', sa.INTEGER(), nullable=True),
    sa.Column('Mon2', sa.INTEGER(), nullable=True),
    sa.Column('Mon3', sa.INTEGER(), nullable=True),
    sa.Column('Mon4', sa.INTEGER(), nullable=True),
    sa.Column('Mon5', sa.INTEGER(), nullable=True),
    sa.Column('Tue1', sa.INTEGER(), nullable=True),
    sa.Column('Tue2', sa.INTEGER(), nullable=True),
    sa.Column('Tue3', sa.INTEGER(), nullable=True),
    sa.Column('Tue4', sa.INTEGER(), nullable=True),
    sa.Column('Tue5', sa.INTEGER(), nullable=True),
    sa.Column('Wed1', sa.INTEGER(), nullable=True),
    sa.Column('Wed2', sa.INTEGER(), nullable=True),
    sa.Column('Wed3', sa.INTEGER(), nullable=True),
    sa.Column('Wed4', sa.INTEGER(), nullable=True),
    sa.Column('Wed5', sa.INTEGER(), nullable=True),
    sa.Column('Thu1', sa.INTEGER(), nullable=True),
    sa.Column('Thu2', sa.INTEGER(), nullable=True),
    sa.Column('Thu3', sa.INTEGER(), nullable=True),
    sa.Column('Thu4', sa.INTEGER(), nullable=True),
    sa.Column('Thu5', sa.INTEGER(), nullable=True),
    sa.Column('Fri1', sa.INTEGER(), nullable=True),
    sa.Column('Fri2', sa.INTEGER(), nullable=True),
    sa.Column('Fri3', sa.INTEGER(), nullable=True),
    sa.Column('Fri4', sa.INTEGER(), nullable=True),
    sa.Column('Fri5', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.branch'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('designation', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dept', sa.VARCHAR(length=30), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('fname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('rollno', sa.VARCHAR(length=30), nullable=True),
    sa.Column('fname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.branch'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('teacher_id', sa.VARCHAR(length=30), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.branch'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment', sa.VARCHAR(length=30), nullable=True),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('rollno', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lab', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['rollno'], ['student.rollno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=4), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=30), nullable=True),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('assignment', sa.VARCHAR(length=30), nullable=True),
    sa.Column('max_marks', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.branch'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
