"""empty message

Revision ID: e3f6e2986a46
Revises: 
Create Date: 2022-06-20 22:22:51.592168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f6e2986a46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=4), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('marks', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('subject', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('subject', sa.Column('teacher', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'teacher', ['teacher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'teacher')
    op.drop_column('subject', 'semester')
    op.drop_column('marks', 'semester')
    op.drop_table('timetable')
    # ### end Alembic commands ###
